# Generated by Django 6.0 on 2026-01-08 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('expert_pose_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('video_uploaded', 'Video Uploaded'), ('pose_extracted', 'Pose Extracted'), ('level1_complete', 'Level-1 Complete'), ('level2_complete', 'Level-2 Complete'), ('level3_complete', 'Level-3 Complete'), ('scoring_complete', 'Scoring Complete'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='RawVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('user_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='PoseArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pose_level1_path', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticalResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('scores_json_path', models.CharField(max_length=255)),
                ('error_metrics_json_path', models.CharField(max_length=255)),
                ('alignment_indices_path', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usersession')),
            ],
        ),
    ]
