# Generated by Django 6.0 on 2026-01-08 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('video_uploaded', 'Video Uploaded'), ('pose_extracted', 'Pose Extracted'), ('level1_complete', 'Level-1 Complete'), ('level2_complete', 'Level-2 Complete'), ('level3_complete', 'Level-3 Complete'), ('scoring_complete', 'Scoring Complete'), ('feedback_generated', 'Feedback Generated'), ('failed', 'Failed')], default='created', max_length=20),
        ),
        migrations.CreateModel(
            name='LLMFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('audio_feedback_path', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('llm_model_used', models.CharField(default='gpt-4', max_length=100)),
                ('user_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usersession')),
            ],
        ),
    ]
